config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get '/about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, 
  presence: true, 
  uniqueness: {case_sensitive: false }, 
  length: { minimum: 3, maximum: 25}
  
  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, 
  presence: true, 
  length: {maximum: 105}, 
  uniqueness: {case_sensitive: false}, 
  format: {with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user  ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    #!! convrts it to boolean and return it.
    !!current_user 
  end

  def require_user
    if !logged_in?
      glash[:danger] = "You must be logged in to perform this action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)

  end

  def new
    @article = Article.new
  end

  def edit
    #@article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    #@article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
    #@article = Article.find(params[:id])
  end

  def destroy
    #@article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "Article was successfully destroyed"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own article"
      redirect_to root_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [ :index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category was updated successfully"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private 
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "you have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] ="There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "you have successfully logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 4)
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    #@user = User.find(params[:id])    
  end

  def update
    #@user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "User account ws updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    #@user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by this user have been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flasf[:danger] = "Only admin users can perform this action"
      redirect_to root_path
    end
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "bd-placeholder-img rounded-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="col-md-6">
      <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
          <h3 class="mb-0">
            <%= link_to article.title, article_path(article) %>
          </h3>
          <div class="mb-1 text-muted">
            <small>Created by: <%= article.user.username if article.user%>, <%= time_ago_in_words(article.created_at) %> ago, 
                    last updated: <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
          <p class="card-text mb-auto"><%= article.description %></p>
          <%= link_to "Continue reading", article_path(article) %>
          <hr /> 

          <% if article.categories.any? %>
            <p>Categories: <%= render article.categories %> </p>
          <% end %>

          <% if logged_in? && (current_user == article.user || current_user.admin?) %>
            <p>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-xs btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            </p>
          <% end %>
        </div>        
      </div>
    </div>
    <% end %>

app/views/articles/_form.html.erb
<div class="container">

  <%= render 'shared/errors', obj: @article%>

  <div>
    <div class="col-xs-12">
      <%= form_for @article do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: 'col-sm-2 col-form-label'%>
          <div class="col-sm-10">
            <%= f.text_field :title, class: 'form-control', placeholder: "Title of the article", autofocus: true %>
          </div>
        </div> 
        <div class="form-group row">
          <%= f.label :description, class: 'col-sm-2 col-form-label'%>
          <div class="col-sm-10">
            <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Body of the article" %>
          </div>
        </div> 
        <div class="form-group row">
          <div class="col-sm-10">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div> 
        
        <div class="form-group row">      
          <div class="col-sm-10">
            <%= f.submit class: "btn btn-primary" %>
          </div>
        </div> 
      <% end %>
      <div class="col-xs-4">
        <%= link_to "Cancel Request", articles_path %>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
  <%= render 'layouts/messages' %>
  <main>
    <h1 align="center" class="display-2"> Edit Existing article </h1>

    <%= render 'form' %>
  </main>

app/views/articles/index.html.erb
  <h1 align="center" class="display-2">Listing all Articles</h1>
  
  <div class="row mb-2">
    <%= render 'article', obj: @articles %>    
  </div>
  
  <div class="pagination justify-content-center">
    <%= will_paginate %>
  </div>

app/views/articles/new.html.erb
  
  <main>
    <h1 align="center" class="display-2"> Create an article </h1>

    <%= render 'form' %>
  </main>

app/views/articles/show.html.erb
  <div align="center">
    <h2>Title: <%=@article.title %></h2>   
    
    <div class="card bg-light text-center col-sm-6">
      <div>
        <% if @article.user %>
          <ul class="listing">
            <li>Created by: </li>
            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
            <li><%= link_to @article.user.username, user_path(@article.user) %></li>
            <li><small><%= pluralize(@article.user.articles.count, "articles") if @article.user.articles %></small></li>
          </ul> 
        <% end %>       
      </div>

      <h4 class="center"><strong>Description :</strong></h4>
      <hr />
      <%= simple_format(@article.description) %>
      <% if @article.categories.any? %>
        <p align="center" class="display-2">Categories: <%= render @article.categories %> </p>
      <% end %>
      <p>
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
          <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(@article), class: "btn btn-xs btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
        <% end %>  
        <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
      </p>
    </div>      
  </div>
  
  

app/views/categories/_category.html.erb
<span class="badge">
  <%= link_to category.name, category_path(category) %> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category%>

  <div>
    <div class="col-xs-12">
      <%= form_for @category do |f| %>
        <div class="form-group">
          <%= f.label :name, class: 'col-sm-2 col-form-label'%>
          <div class="col-sm-10">
            <%= f.text_field :name, class: 'form-control', placeholder: "Enter category name", autofocus: true %>
          </div>
        </div>        
        <div class="form-group">      
          <div class="col-sm-10">
            <%= f.submit class: "btn btn-primary" %>
          </div>
        </div> 
      <% end %>
      <div class="col-xs-4">
        <%= link_to "Cancel Request", articles_path %>
      </div>
    </div>
  </div>

app/views/categories/edit.html.erb
<div class="container">

  <h1 align="center" class="display-2">Edit Category</h1>

  <%= render 'form'%>  

</div>

app/views/categories/index.html.erb
<div class="container">

  <h1 align="center" class="display-2">Listing all categories</h1>

  <div class="">
    <% @categories.each do |category| %>
      <ul class="listing">
        <div class="text-center">
          <div class="card text-white bg-dark mb-3">
            <div class="card-body">
              <li>
                <%= link_to "#{category.name}", category_path(category) %>
              </li>
              <li><small><%= pluralize(category.articles.count, "article") %></small></li>
            </div>
          </div>
        </div>
      </ul>
    <% end %>
  </div>

  <div class="pagination justify-content-center">
    <%= will_paginate %>
  </div>
  
</div>

app/views/categories/new.html.erb
<div class="container">

  <h1 align="center" class="display-2">Create New Category</h1>

  <%= render 'form'%>    

</div>

app/views/categories/show.html.erb
<h1 align="center" class="display-2"><%= "Category: " + @category.name %> </h1> 
<% if logged_in? and current_user.admin? %>
  <span class="badge"><%= link_to "Edit Category", edit_category_path(@category)%> </span>
<% end %>
<div class="row mb-2">
  <%= render 'articles/article', obj: @category_articles %>    
</div>

<div align="center">
  <%= will_paginate @category_articles %>
</div>
  

app/views/layouts/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "Home", root_path%>
    </p>
    <p>Blog example is &copy; Arshdeep Singh for learing Ruby on Rails</p>
    <p>Alpha blog for new Bloggers, by <a href="http://www.arshdeeprangi.com">Arshdeep Singh</a></p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div>
  <div class="conatiner">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "Alpha Blog", root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample07">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Users", users_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: 'nav-link'%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">     
            <%= link_to "All Categories", categories_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div> 
            <% Category.all.each do |category| %>
              <%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %>
            <% end %>           
          </div>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "New Article", new_article_path, class: 'nav-link'%>
          </li>
        <% end %>
      </ul>

      <ul class="navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Your Profile <%= 'Admin' if current_user.admin?%>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
              <% if current_user.admin?%>
                <div class="dropdown-divider"></div>
                <%= link_to "Add Category", new_category_path, class: "dropdown-item" %>
              <% end %>              
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, method: :delete, class: 'nav-link'%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: 'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path, class: 'nav-link'%>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    
    <div id="main-div" class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer'%>

    <!-- <%= debug(params) if Rails.env.development? %> -->
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is alpha blog about page</h1>

<%= link_to 'Home', root_path  %>

app/views/pages/home.html.erb

<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Ruby Thoughts!!! </h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    <p>
      <%= link_to "Sign up now", signup_path, class: 'btn btn-primary my-2'%>
    </p>
  </div>
</section> 



app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div>
    <div class="container">
      <div class="alert alert-danger" role="alert">
        <h2 class="alert-heading">Oops! Something went wrong</h2>
        <p><%= pluralize(obj.errors.count, "error") %>
          prohibited this article from being saved:</p>
        <hr>
        <% obj.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>

  <div>
    <div class="col-xs-12">
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :username, class: 'col-sm-2 col-form-label'%>
          <div class="col-sm-10">
            <%= f.text_field :username, class: 'form-control', placeholder: "Enter user name", autofocus: true %>
          </div>
        </div> 
        <div class="form-group">
          <%= f.label :email, class: 'col-sm-2 col-form-label'%>
          <div class="col-sm-10">
            <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password, class: 'col-sm-2 col-form-label'%>
          <div class="col-sm-10">
            <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
          </div>
        </div> 
        
        <div class="form-group">      
          <div class="col-sm-10">
            <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary") %>
          </div>
        </div> 
      <% end %>
      <div class="col-xs-4">
        <%= link_to "Cancel Request", articles_path %>
      </div>
    </div>
  </div>

app/views/users/edit.html.erb
<div class="container">

  <h1 align="center" class="display-2">Edit your details </h1>
  
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">

  <h1 align="center" class="display-2">All Alpha Bloggers </h1>
    <div align="center">
    <% @users.each do |user| %>
      
        <div class="card bg-light text-center col-sm-6">
          <div class="card-body">
            <ul class="listing">
              <li><%= link_to gravatar_for(user), user_path(user) %></li>
              <li><%= link_to user.username, user_path(user) %></li>
              <li><small><%= pluralize(user.articles.count, "articles") if user.articles %></small></li>
              <% if logged_in? and current_user.admin? %>
                <li><%= link_to "Delete this user",user_path(user), 
                method: :delete, 
                data: { confirm: "Are you sure you want to delete this user and all articles associated with this user"} %></li>
              <% end %>
            </ul>    
          </div>
        </div>
      
    <% end %>

    <div class="pagination justify-content-center">
      <%= will_paginate %>
    </div>

    </div>  
  
</div>

app/views/users/new.html.erb
<div class="container">

  <h1 align="center" class="display-2">Sign up for Alpha Blog </h1>
  
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">

  <h1 align="center" class="display-2">Welcome to <%= @user.username%>'s page </h1>

  <div class="row">
      <div class="col-lg text-center">
        <%= gravatar_for @user, size: 150 %>
        <h4><%= @user.username%>'s articles </h4>
        <%= render 'articles/article', obj: @user_articles %>
        <%= will_paginate @user_articles %>
      </div>
  </div>
  
</div>